### ISSUE TITLE
Milestone Goals

### ISSUE THREAD

**Issue by hentai-chan** [hentai-chan/lolicon#4]
- [x] Implement basic (i.e. cryptographically insecure) encryption methods in the `lolicon.compsi.cryptography` namespace 
- [x] extend the number of available constants in `lolicon.constants`
- [x] Improve doc strings where necessary
- [x] move the `Planet` and `Sattelite` classes to `lolicon.physics.astronomy`.

**Comment by hentai-chan** [comment]
In `mathematics.py`, implement the following functions:
- [ ] `sieve_of_eratosthenes`
- [ ] `pi_series`
- [ ] `euler_series`
- [ ] `golden_ratio`

**Comment by hentai-chan** [comment]
Closed with 167ce78.
